fix: module resolution
byu-oit/express-logger pull request #188
Opened 2024-04-10 17:17 UTC by ggemre

2024-04-14 02:46 UTC, stuft2 requested changes

2024-04-14 02:46 UTC, stuft2 commented on tsconfig.json
> -    "esModuleInterop": true,
Still requires this

2024-04-15 17:35 UTC, ggemre commented on tsconfig.json
> -    "esModuleInterop": true,
oops thanks that was removed by mistake

2024-04-24 14:13 UTC, stuft2 approved these changes

2024-05-13 18:16 UTC, merged